// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvrtyizkiabmisswlotq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cnR5aXpraWFibWlzc3dsb3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDk4MjEsImV4cCI6MjA2NzQ4NTgyMX0.VvAlNhLH-q1zv5FIRkEtf0Gx8fCyD0fQ9IeGXwFj-_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});